name: Sync Nixtlaverse common docs 

on:
  push:
    branches: [main]

jobs:
  sync-contributing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        library: [statsforecast, mlforecast, neuralforecast, hierarchicalforecast]
    steps:
    - name: Sync Repos Action
      uses: FedericoGarza/sync-repos@v1.0.1
      with: 
        output-repo: ${{ matrix.library }}
        output-file: CONTRIBUTING.md
        input-file: docs/contribute/step-by-step.md
        branch-name: feat/update-contributing-file
        user-email: ${{ secrets.USER_EMAIL }}
        user-name: ${{ secrets.USER_NAME }}
        github-token: ${{ secrets.TOKEN_GITHUB }}
        commit-message: "Synchronize CONTRIBUTING.md nixtla-commons - Triggered by Github Workflows"
