name: Sync Nixtlaverse common docs 

on:
  push:
    branches: [main]

jobs:
  sync-contributing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        library: [statsforecast]
    steps:
    - name: Sync Repos Action
      uses: FedericoGarza/sync-repos@v1.0.6
      with: 
        output-repo: Nixtla/${{ matrix.library }}
        output-file: nbs/docs/contribute/
        input-file: docs/contribute/*
        branch-name: feat/update-contributing-file
        base-branch: feat/new-docs-structure
        user-email: ${{ secrets.USER_EMAIL }}
        user-name: ${{ secrets.USER_NAME }}
        github-token: ${{ secrets.TOKEN_GITHUB }}
        commit-message: "[docs]: synchronize contribute from nixtla-commons - Triggered by Github Workflows"

  sync-styles:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        library: [statsforecast]
    steps:
    - name: Sync Repos Action
      uses: FedericoGarza/sync-repos@v1.0.6
      with: 
        output-repo: Nixtla/${{ matrix.library }}
        output-file: nbs/
        input-file: styles/*
        branch-name: feat/update-styles
        base-branch: feat/new-docs-structure
        user-email: ${{ secrets.USER_EMAIL }}
        user-name: ${{ secrets.USER_NAME }}
        github-token: ${{ secrets.TOKEN_GITHUB }}
        commit-message: "[docs]: synchronize styles from nixtla-commons - Triggered by Github Workflows"
