name: Sync Nixtlaverse common docs 

on:
  push:
    branches: [main]

jobs:
  sync-contributing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          contributing:
            - 'docs/contribute/step-by-step.md'
    # run only if 'contributing' files were changed
    - name: "Update CONTRIBUTING.md"
      if: steps.filter.outputs.contributing == 'true'
      run : |
          echo "[LOG] Setup global config"
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "${{ secrets.USER_NAME }}"
          echo "[LOG] It contains changes to the contributing guide, will update to other repo"
          cd ./docs/contribute
          echo "[LOG] Cloning StatsForecast repo"
          git clone https://github.com/nixtla/statsforecast.git temp
          echo "[LOG] Copying contributing file"
          cp step-by-step.md temp/CONTRIBUTING.md
          cd temp
          echo "[LOG] Git set-url remote repository"
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN_GITHUB }}@github.com/Nixtla/statsforecast
          echo "[LOG] Remove previous branch"
          git push origin --delete feat/update-contributing-file
          echo "[LOG] Create new branch"
          git checkout -b feat/update-contributing-file
          echo "[LOG] Git add ."
          git add .
          echo "[LOG] Git Commit"
          git commit -m "Synchronize CONTRIBUTING.md nixtla-commons - Triggered by Github Workflows"
          echo "[LOG] Push"
          git push --set-upstream origin feat/update-contributing-file
          echo "[LOG] Create PR"
          gh pr create -H feat/update-contributing-file -B main --title 'Update CONTRIBUTING.md file' --body 'Created by Github action'
          echo "[LOG] Remove Folder"
          cd ..
          rm -rf temp
      env: 
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
